Forum/urls.py
__author__ = 'Jordan'

from django.conf.urls import patterns, include, url
from django.contrib import admin
from .views import index, IndexListCategoryView, IndexCategoryView, DetailForumView, DetailThreadView, CreateThreadView, \
    CreatePostView

urlpatterns = patterns('',
    url(r'^$', IndexListCategoryView.as_view(), name='super_portal_index'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/$', IndexCategoryView.as_view(), name='category_detail_forum'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/$', DetailForumView.as_view(), name='forum_detail'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/create/$', CreateThreadView.as_view(), name='create_thread'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<thread_name>(?:\w+[-\t\n\r\f\v:]*\w+)+)/$', DetailThreadView.as_view(), name='thread_detail'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<thread_name>(?:\w+[-\t\n\r\f\v:]*\w+)+)/new/$', CreatePostView.as_view(), name='create_post'),

)

GuildPortal/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Portal.views import index
from django.contrib.auth import views as auth_view
from PortalAdmin.views import SignupView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'GuildPortal.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^forum/', include('Forum.urls')),
    url(r'^message/', include('PortalMessaging.urls')),
    url(r'^raid/', include('PortalRaid.urls')),
    url(r'^recrutement/', include('PortalEnrollment.urls')),
    url(r'^administration/', include('PortalAdmin.urls')),
    url(r'^accounts/login/', auth_view.login),
                       url(r"^account/signup/$",
                           SignupView.as_view(),
                           name="account_signup"),
    # url(r"^account/", include("account.urls")),
    url(r'', include('SuperPortal.urls')),
)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^media/news/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    }),
)

PortalRaid/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext as _

# Create your models here.
from Portal.models import Game, CharacterAttribute


class CharacterModel(models.Model):
    user = models.ForeignKey(User)
    game = models.ForeignKey(Game, blank=True, null=True)
    name = models.CharField(_('Name'), max_length=50)
    server = models.ForeignKey('Realm')
    iLvl = models.IntegerField(_('iLvl'), default=0, null=True)
    url = models.URLField(null=True, blank=True)
    classCharacter = models.ManyToManyField(CharacterAttribute, verbose_name=_("Class for your character"))

    def __str__(self):
        return "%s: %s - %s : %s" % (self.user.username, self.name, self.game.name, self.server.name)

    class Meta:
        ordering = ('user',)
        verbose_name = _('Character')
        verbose_name_plural = _('Characters')


class Realm(models.Model):
    #TODO Faire une update admin pour remplir automatiquement
    game = models.ForeignKey(Game, blank=True, null=True)
    name = models.CharField(_('Realm name'), max_length=50)

    def __str__(self):
        return "%s - %s" %(self.game, self.name)

    class Meta:
        ordering = ('game',)
        verbose_name = _('Realm')
        verbose_name_plural = _('Realms')


class Raid(models.Model):
    name = models.CharField(_('Raid name'), max_length=64)
    game = models.ForeignKey(Game)
    lvl = models.ForeignKey('RaidLvl', null=True)
    number_of_boss = models.SmallIntegerField(_('Number of boss'))
    boss_successful = models.SmallIntegerField(_('Boss Successful'))
    image = models.ImageField(_('Image'), upload_to='portalraid/image/')

    def class_formatted_level(self):
        return self.lvl.name.replace(' ', '-')

    def get_progression_boss(self):
        return self.boss_successful * 100 / self.number_of_boss

    def get_out_raid(self):
        return self.outraid_set.all()

    def __str__(self):
        return "%s, %s - %s" % (self.name, self.game.name, self.lvl.name)

class Boss(models.Model):
    name = models.CharField(_('Boss name'), max_length=64)
    raid = models.ManyToManyField(Raid)
    position_in_raid = models.SmallIntegerField(_('Position in raid'), default=1)
    story = models.TextField(_('Story about this boss'))
    image = models.ImageField(_('Image'), upload_to='portalraid/boss/')

    def __str__(self):
        return "%s - %s" % (self.name, self.raid.name)

class RaidLvl(models.Model):
    name = models.CharField(_('Level name'), max_length=64, help_text=_("Normal mode, Heroic mode, Mythic mode"))

    def __str__(self):
        return "%s" % self.name

class GroupForRaid(models.Model):
    name = models.CharField(_('Name'), max_length=64)
    users = models.ManyToManyField(CharacterModel)


class ClassForOutRaid(models.Model):
    number = models.SmallIntegerField()
    classCharacter = models.ForeignKey(CharacterAttribute)

    def __str__(self):
        return "%d %s" % (self.number, self.classCharacter.attribute_value)

from datetime import datetime

class OutRaid(models.Model):
    name = models.CharField(_('Out name'), max_length=64)
    raid = models.ForeignKey(Raid)
    raid_lvl = models.ForeignKey(RaidLvl)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    creator = models.ForeignKey(User)
    class_needed = models.ManyToManyField(ClassForOutRaid)
    lvl = models.SmallIntegerField(_('Level'))

    def __str__(self):
        return "%s - %s => %s for %s" % (self.start_date, self.end_date, self.name, self.raid.name)

    def check_character_in(self, character):
        for character_out in self.characterforoutraid_set.all():
            if character == character_out.character:
                return True
        return False

    def get_characters(self):
        return self.characterforoutraid_set.all()

    def can_be_register(self):
        if self.start_date < datetime.now():
            return False
        return True

class CharacterForOutRaid(models.Model):
    out_raid = models.ForeignKey(OutRaid, blank=True, null=True)
    character = models.ForeignKey(CharacterModel)
    classCharacter = models.ForeignKey(CharacterAttribute)
    present = models.BooleanField(default=False)

templates/Administration/games/add_character_attibutes.html
{% extends 'Administration/admin_base.html' %}
{% load i18n %}
{% block body_title %}
    {% trans 'Add character attributes' %}
{% endblock %}
{% block body %}
    <form role="form" method="post">
    {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-default">{% trans 'Submit' %}</button>
    </form>

{% endblock %}

templates/Administration/games/game_add.html
{% extends 'Administration/admin_base.html' %}
{% load i18n %}
{% block body_title %}
    {% trans 'Add new Games' %}
{% endblock %}

{% block body %}
    <div class="col-lg-4 col-md-7 col-xs-12">
        <form role="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    </div>

    <div class="clearfix visible-lg-block"></div>

{% endblock %}

templates/Administration/games/game_detail.html
{% extends 'Administration/admin_base.html' %}
{% load i18n %}
{% load static %}
{% block css %}
    <!-- DataTables CSS -->
    <link href="{% static 'PortalAdmin/css/external/dataTables.bootstrap.css' %}" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="{% static 'PortalAdmin/css/external/dataTables.responsive.css' %}" rel="stylesheet">
{% endblock %}
{% block body_title %}
    {% trans 'Details for' %} {{ game.name }} - <a href="{% url 'admin_game_update' pk=game.pk %}"><i class="fa fa-cogs"></i></a>
{% endblock %}

{% block body %}
    {#    <div class="user-profile row">#}
    <div class="col-lg-4 col-xs-12 col-md-5">
        <img class="img-responsive" src="{{ game.image.url }}">
    </div>
    <div class="user col-lg-4 col-md-7 col-xs-12">
    <h3>{% trans 'Informations' %}</h3>
        <p>{% trans 'Name' %}: {{ game.name }}</p>
        <p>{% trans 'Url API' %}: {{ game.url_api }}</p>
        <p>{% trans 'Number of players' %}: {{ game.userprofile_set.all|length }}</p>
        <p>{% trans 'Percentage player' %}: {{ game.percent_of_player }} %</p>
        <p>{% trans 'Number of raid output' %}: {{ game.get_out_raid|length }}</p>
    </div>
   <div id="raids-list" class="col-lg-4">
        <h3>{% trans 'Raids list' %}</h3>
        {% for raid in game.raid_set.all %}
            <div class="raid">
                {{ raid.name }} - {{ raid.lvl }}
            </div>
        {% endfor %}
    </div>
    <div class="clearfix visible-lg-block"></div>




    <div class="col-lg-12">
    <h3>{% trans 'Raids output list' %}</h3>
        <div class="panel panel-default">
            <div class="panel-heading">
                {% trans 'Raid output list' %}
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" role="grid" aria-describedby="dataTables-example_info">
                                    <thead>
                                    <tr role="row">
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column descending" style="width: 280px;">{% trans 'Raid name' %}</th>
                                        <th class="sorting_asc" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Browser: activate to sort column ascending" style="width: 338px;">{% trans 'Start date' %}</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 315px;">{% trans 'End date' %}</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 243px;">{% trans 'Raid' %}</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 191px;">{% trans 'Raid lvl' %}</th></tr>
                                    </thead>
                                    <tbody>
                                    {% for out_raid in game.get_out_raid %}
                                        <tr class="gradeA {% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}" role="row">
                                            <td><a href="{% url 'admin_raid_out_details' pk_game=game.pk pk_raid=out_raid.pk %}">{{ out_raid.name }}</a></td>
                                            <td>{{ out_raid.start_date|date:'D d F o' }} {{ out_raid.start_date|date:'H:i' }}</td>
                                            <td>{{ out_raid.end_date|date:'D d F o' }} {{ out_raid.end_date|date:'H:i' }}</td>
                                            <td>{{ out_raid.raid.name }}</td>
                                            <td>{{ out_raid.raid.lvl }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                {#                                <div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">Showing 1 to 10 of {{ user_list|length }} entries</div></div><div class="col-sm-6"><div class="dataTables_paginate paging_simple_numbers" id="dataTables-example_paginate"><ul class="pagination"><li class="paginate_button previous disabled" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_previous"><a href="#">Previous</a></li><li class="paginate_button active" aria-controls="dataTables-example" tabindex="0"><a href="#">1</a></li><li class="paginate_button " aria-controls="dataTables-example" tabindex="0"><a href="#">2</a></li><li class="paginate_button " aria-controls="dataTables-example" tabindex="0"><a href="#">3</a></li><li class="paginate_button " aria-controls="dataTables-example" tabindex="0"><a href="#">4</a></li><li class="paginate_button " aria-controls="dataTables-example" tabindex="0"><a href="#">5</a></li><li class="paginate_button " aria-controls="dataTables-example" tabindex="0"><a href="#">6</a></li><li class="paginate_button next" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_next"><a href="#">Next</a></li></ul></div></div></div></div>#}
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function() {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>

    <!-- DataTables JavaScript -->
    <script src="{% static 'PortalAdmin/js/external/jquery.dataTables.js' %}"></script>
    <script src="{% static 'PortalAdmin/js/external/dataTables.bootstrap.min.js' %}"></script>
{% endblock %}

templates/Administration/games/game_edit_detail.html
{% extends 'Administration/admin_base.html' %}
{% load i18n %}
{% block body_title %}
    {% trans 'Game edit' %}
{% endblock %}

{% block body %}
    <div class="col-lg-4 col-md-7 col-xs-12">
        <form role="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    </div>

    <div class="clearfix visible-lg-block"></div>
{% endblock %}

templates/Administration/games/game_list.html
{% extends 'Administration/admin_base.html' %}
{% load i18n %}
{% block body_title %}
    {% trans 'Game list' %} -- <a href="{% url 'admin_games_add' %}"><i class="fa fa-plus"></i></a>
{% endblock %}
{% block body %}
    {% for game in game_list %}
        <div class="game">
            <h3><img src="{{ game.image.url }}" height="100"> {{ game.name }} <a href="{% url 'admin_game_detail' pk=game.pk %}"><i class="fa fa-cogs"></i></a></h3>
        </div>
    {% endfor %}
{% endblock %}

templates/Administration/games/game_unit_for_li.html
<div class="game-unit-for-li">
    <p><img class="img-game-unit-for-li" height="40" width="40" src="{{ game.image.url }}" style="vertical-align: middle;"> {{ game.name }}</p>
</div>