Forum/urls.py
__author__ = 'Jordan'

from django.conf.urls import patterns, include, url
from django.contrib import admin
from .views import index, IndexListCategoryView, IndexCategoryView, DetailForumView, DetailThreadView, CreateThreadView, \
    CreatePostView

urlpatterns = patterns('',
    url(r'^$', IndexListCategoryView.as_view(), name='super_portal_index'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/$', IndexCategoryView.as_view(), name='category_detail_forum'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/$', DetailForumView.as_view(), name='forum_detail'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/create/$', CreateThreadView.as_view(), name='create_thread'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<thread_name>(?:\w+[-\t\n\r\f\v:]*\w+)+)/$', DetailThreadView.as_view(), name='thread_detail'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<thread_name>(?:\w+[-\t\n\r\f\v:]*\w+)+)/new/$', CreatePostView.as_view(), name='create_post'),

)

GuildPortal/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Portal.views import index
from django.contrib.auth import views as auth_view
from PortalAdmin.views import SignupView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'GuildPortal.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^forum/', include('Forum.urls')),
    url(r'^message/', include('PortalMessaging.urls')),
    url(r'^raid/', include('PortalRaid.urls')),
    url(r'^recrutement/', include('PortalEnrollment.urls')),
    url(r'^administration/', include('PortalAdmin.urls')),
    url(r'^accounts/login/', auth_view.login),
                       url(r"^account/signup/$",
                           SignupView.as_view(),
                           name="account_signup"),
    # url(r"^account/", include("account.urls")),
    url(r'', include('SuperPortal.urls')),
)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^media/news/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    }),
)

SuperPortal/urls.py
__author__ = 'Jordan'

from django.conf.urls import patterns, include, url
from .views import index, Profile, Members
from Forum.views import index as forum_index

urlpatterns = patterns('',
    url(r'^$', index, name='super_portal_index'),
    url(r'^forum/$', forum_index, name='forum_index'),
    url(r'^profile/$', Profile.as_view(), name='profile'),
    url(r'^profile/(?P<pk>(?:\d+))/$', Profile.as_view(), name='profile_user'),
    url(r'^members/$', Members.as_view(), name='members'),
    url(r'^(?P<portal_name>(?:\w+[-\s*]*(\w+)*)+)/', include('Portal.urls')),
)

PortalRaid/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext as _

# Create your models here.
from Portal.models import Game, CharacterAttribute


class CharacterModel(models.Model):
    user = models.ForeignKey(User)
    game = models.ForeignKey(Game, blank=True, null=True)
    name = models.CharField(_('Name'), max_length=50)
    server = models.ForeignKey('Realm')
    iLvl = models.IntegerField(_('iLvl'), default=0, null=True)
    url = models.URLField(null=True, blank=True)
    classCharacter = models.ManyToManyField(CharacterAttribute, verbose_name=_("Class for your character"))

    def __str__(self):
        return "%s: %s - %s : %s" % (self.user.username, self.name, self.game.name, self.server.name)

    class Meta:
        ordering = ('user',)
        verbose_name = _('Character')
        verbose_name_plural = _('Characters')


class Realm(models.Model):
    #TODO Faire une update admin pour remplir automatiquement
    game = models.ForeignKey(Game, blank=True, null=True)
    name = models.CharField(_('Realm name'), max_length=50)

    def __str__(self):
        return "%s - %s" %(self.game, self.name)

    class Meta:
        ordering = ('game',)
        verbose_name = _('Realm')
        verbose_name_plural = _('Realms')


class Raid(models.Model):
    name = models.CharField(_('Raid name'), max_length=64)
    game = models.ForeignKey(Game)
    lvl = models.ForeignKey('RaidLvl', null=True)
    number_of_boss = models.SmallIntegerField(_('Number of boss'))
    boss_successful = models.SmallIntegerField(_('Boss Successful'))
    image = models.ImageField(_('Image'), upload_to='portalraid/image/')

    def class_formatted_level(self):
        return self.lvl.name.replace(' ', '-')

    def get_progression_boss(self):
        return self.boss_successful * 100 / self.number_of_boss

    def get_out_raid(self):
        return self.outraid_set.all()

    def __str__(self):
        return "%s, %s - %s" % (self.name, self.game.name, self.lvl.name)

class Boss(models.Model):
    name = models.CharField(_('Boss name'), max_length=64)
    raid = models.ManyToManyField(Raid)
    position_in_raid = models.SmallIntegerField(_('Position in raid'), default=1)
    story = models.TextField(_('Story about this boss'))
    image = models.ImageField(_('Image'), upload_to='portalraid/boss/')

    def __str__(self):
        return "%s - %s" % (self.name, self.raid.name)

class RaidLvl(models.Model):
    name = models.CharField(_('Level name'), max_length=64, help_text=_("Normal mode, Heroic mode, Mythic mode"))

    def __str__(self):
        return "%s" % self.name

class GroupForRaid(models.Model):
    name = models.CharField(_('Name'), max_length=64)
    users = models.ManyToManyField(CharacterModel)


class ClassForOutRaid(models.Model):
    number = models.SmallIntegerField()
    classCharacter = models.ForeignKey(CharacterAttribute)

    def __str__(self):
        return "%d %s" % (self.number, self.classCharacter.attribute_value)

from datetime import datetime

class OutRaid(models.Model):
    name = models.CharField(_('Out name'), max_length=64)
    raid = models.ForeignKey(Raid)
    raid_lvl = models.ForeignKey(RaidLvl)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    creator = models.ForeignKey(User)
    class_needed = models.ManyToManyField(ClassForOutRaid)
    lvl = models.SmallIntegerField(_('Level'))

    def __str__(self):
        return "%s - %s => %s for %s" % (self.start_date, self.end_date, self.name, self.raid.name)

    def check_character_in(self, character):
        for character_out in self.characterforoutraid_set.all():
            if character == character_out.character:
                return True
        return False

    def get_characters(self):
        return self.characterforoutraid_set.all()

    def can_be_register(self):
        if self.start_date < datetime.now():
            return False
        return True

class CharacterForOutRaid(models.Model):
    out_raid = models.ForeignKey(OutRaid, blank=True, null=True)
    character = models.ForeignKey(CharacterModel)
    classCharacter = models.ForeignKey(CharacterAttribute)
    present = models.BooleanField(default=False)

SuperPortal/models/settings.py
__author__ = 'Alexandre Cloquet'

from django.contrib.auth.models import User, Group
from django.db import models
from django.utils.translation import ugettext as _
from uuid import uuid4


from Portal.models import Category


class GuildSettings(models.Model):
    '''
    Handle all settings about guild and SuperPortal
    '''
    guild_name = models.CharField(_('Guild name'), max_length=120)
    guild_motto = models.CharField(_('Guild motto'), max_length=256)
    guild_chief = models.ForeignKey(User)
    short_guild_description = models.CharField(_("Short description about your guild"), max_length=120, default="")
    guild_description = models.TextField(_("Description about your guild"), default="")
    tag = models.CharField(_('Tag'), max_length=10, default="")
    forum_active = models.BooleanField(_('Forum active'), default=True)
    slider_active = models.BooleanField(_('Slider active'), default=False)
    youtube_channel = models.URLField(_('Youtube channel'), default="", blank=True, null=True)
    twitch_channel = models.CharField(_('Twitch channel'), default="", blank=True, null=True, max_length=50)
    facebook_page = models.URLField(_('Facebook Page'), default="", blank=True, null=True)
    twitter_page = models.URLField(_('Twitter page'), default="", blank=True, null=True)
    category_slider = models.ForeignKey(Category, blank=True, null=True)
    group_can_vote = models.ManyToManyField(Group, blank=True, related_name='group_can_vote')
    group_can_write_news = models.ManyToManyField(Group, blank=True, related_name='group_can_write_news')
    group_can_write_wiki = models.ManyToManyField(Group, blank=True, related_name='group_can_write_wiki')
    icon_guild = models.ImageField(upload_to='superportal/setting', blank=True, null=True)

    class Meta:
        verbose_name = _('Guild Settings')
        verbose_name_plural = _('Guild Settings')

    def __str__(self):
        return u"[%s][%s] %s - %s" % (self.tag, self.guild_name, self.guild_motto, self.guild_chief.username)

SuperPortal/models/superportal.py
from uuid import uuid4

__author__ = 'Alexandre Cloquet'

from django.db import models
from django.utils.translation import ugettext as _


class SuperPortal(models.Model):
    id_uuid = models.CharField(max_length=36, primary_key=True,
                          default=str(uuid4()), editable=False)
    banner = models.ImageField(_('Banner'), upload_to='superportal/banner', blank=True, null=True)

SuperPortal/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView

from .models import GuildSettings
from Portal.models import News, Userprofile
from PortalEnrollment.models import EnrollmentSettings
# Create your views here.


def index(request):
    context = {}
    context['short_description'] = GuildSettings.objects.all().first().short_guild_description
    # context['list_portal'] = Portal.objects.all()
    context['news_list'] = News.objects.filter(published=True).order_by('-published_date')
    context['enrollments'] = EnrollmentSettings.openned_enrollement.all()

    return render(request, "SuperPortal/index.html", context=context)


class Profile(TemplateView):
    template_name = 'SuperPortal/profile/index.html'

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)


class Members(ListView):
    model = Userprofile
    template_name = 'SuperPortal/members.html'

templates/SuperPortal/profile/index.html
{% extends 'SuperPortal/base.html' %}
{% load i18n %}
{% load static %}
{% block css %}
    {{ block.super }}

    <link rel="stylesheet" href="{% static 'PortalRaid/css/profil.css' %}">
{% endblock %}
{% block meta_description %}{% trans 'Profile' %}: {{ user.username }}{% endblock %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function () {
                    target = Array();
                    $('img#thumbnail-character').each(function (x) {
                        target[x] = $(this);
                        $.ajax({
                            url: '{% url 'detail_characters_from_api' %}' + "?char=" + $(this).attr('data-id'),
                            type: 'GET',
                            dataType: 'json'
                        }).success(function(data){
                            target[x].attr('src', "http://eu.battle.net/static-render/eu/" + data.thumbnail);
                        });
                    });
                }
        );
    </script>
{% endblock %}
{% block body %}
    <div class="col-xs-10 col-xs-offset-1 content-wrapper">


            <a href="#">{% trans 'Change profile' %}</a> |
            <a href="{% url 'new_character' %}">{% trans 'Add new character' %}</a>
            <div id="profile" class="col-xs-8">

                <div id="img-profile" class="col-xs-3">

                    {% if user.userprofile.image_profile %}
                        <img src="{{ user.userprofile.image_profile.url }}" height="190" width="190">
                    {% endif %}
                    {% for game in user.userprofile.games.all %}
                        <img src="{{ game.image_thumbnail.url }}" class="" height="20px" width="20px"/> {{ game.name }}
                    {% endfor %}
                <hr>
                    {% for group in user.groups.all %}
                        <h5>{{ group }}</h5>
                    {% endfor %}
                </div>

                <div id="info-profile" class="col-xs-5">
                    <h4>{{ user.username|title }}, {{ user.userprofile.gender }} {% if user.userprofile.birthday_date  %} - {{ user.userprofile.age }} {% trans 'years' %}{% endif %}</h4>
                    <p>Job/Study : {{ user.userprofile.job_study }}</p>
                    <p>User : {{ user.userprofile.town }} {% trans 'in' %} {{ user.userprofile.country }}</p>
                    <p>Teamspeak : {{ user.userprofile.teamspeak_nickname }}</p>
                    <p>Mumble : {{ user.userprofile.mumble_nickname }}</p>
                    <p>Skype : {{ user.userprofile.skype_nickname }}</p>
                    <p>Twitch : {{ user.userprofile.twitch_page }}</p>
                    <p>Dailymotion : {{ user.userprofile.dailymotion_stream_page }}</p>
                </div>
                <div class="col-xs-12">
                    <p>{{ user.userprofile.about_you|linebreaks }}</p>
                </div>
            </div>
            <div id="characters_list" class="col-xs-4">
                <h2>{% trans 'Characters list' %}:</h2>
                {% for character in user.charactermodel_set.all %}
                    <div id="character-thumbnail" class="col-xs-2" style="padding-right:80px;">
                        <a href="{% url 'detail_characters' character.id %}"><img id="thumbnail-character" src="{% static 'PortalEnrollment/loader/723.GIF'%}" data-id="{{ character.id }}"></a>
                    </div>
                {% endfor %}
            </div>
        </div>


{% endblock %}