Forum/urls.py
__author__ = 'Jordan'

from django.conf.urls import patterns, include, url
from django.contrib import admin
from .views import index, IndexListCategoryView, IndexCategoryView, DetailForumView, DetailThreadView, CreateThreadView, \
    CreatePostView

urlpatterns = patterns('',
    url(r'^$', IndexListCategoryView.as_view(), name='super_portal_index'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/$', IndexCategoryView.as_view(), name='category_detail_forum'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/$', DetailForumView.as_view(), name='forum_detail'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/create/$', CreateThreadView.as_view(), name='create_thread'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<thread_name>(?:\w+[-\t\n\r\f\v:]*\w+)+)/$', DetailThreadView.as_view(), name='thread_detail'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<thread_name>(?:\w+[-\t\n\r\f\v:]*\w+)+)/new/$', CreatePostView.as_view(), name='create_post'),

)

GuildPortal/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Portal.views import index
from django.contrib.auth import views as auth_view
from PortalAdmin.views import SignupView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'GuildPortal.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^forum/', include('Forum.urls')),
    url(r'^message/', include('PortalMessaging.urls')),
    url(r'^raid/', include('PortalRaid.urls')),
    url(r'^recrutement/', include('PortalEnrollment.urls')),
    url(r'^administration/', include('PortalAdmin.urls')),
    url(r'^accounts/login/', auth_view.login),
                       url(r"^account/signup/$",
                           SignupView.as_view(),
                           name="account_signup"),
    # url(r"^account/", include("account.urls")),
    url(r'', include('SuperPortal.urls')),
)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^media/news/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    }),
)

Forum/models.py
import datetime
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.template.defaultfilters import first
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from GuildPortal import settings


class Category(models.Model):
    name = models.CharField(_('Category'), max_length=150)
    slug = models.CharField(_('Slug'), max_length=150, db_index=True, blank=True)
    position = models.SmallIntegerField(_('Position'))

    class Meta:
        ordering = ["position"]
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return "%s" % self.name

class Forum(models.Model):
    title = models.CharField(_('Title'), max_length=80)
    slug = models.CharField(_('Slug'), max_length=80, db_index=True, blank=True)
    description = models.CharField(_('Description'), max_length=80, blank=True)
    position = models.SmallIntegerField(_('Position'))
    category = models.ForeignKey(Category, related_name="forums")
    closed = models.BooleanField(_('Closed'), default=False)
    view_count = models.IntegerField(default=0, editable=False)
    post_count = models.IntegerField(default=0, editable=False)
    image = models.ImageField(upload_to='forum/forum', blank=True)

    class Meta:
        ordering = ["position"]
        verbose_name = _('Forum')
        verbose_name_plural = _('Forums')

    def __str__(self):
        return "%s" % self.title

    def num_posts(self):
        return sum([t.num_posts() for t in self.threads.all()])

    def last_post(self):
        """Go over the list of threads and find the most recent post."""
        threads = self.threads.all()
        last = None
        for thread in threads:
            lastp = thread.last_post()
            if lastp and (not last or lastp.created > last.created):
                last = lastp
        return last

    def update_post_count(self):
        post_count = 0
        for thread in self.threads.all():
            thread.update_reply_count()
            post_count += thread.reply_count + 1  # add one for the thread itself
        self.post_count = post_count
        self.save()

class Thread(models.Model):
    title = models.CharField(max_length=60)
    slug = models.CharField(max_length=60, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, blank=True, null=True)
    forum = models.ForeignKey(Forum, related_name="threads")
    view_count = models.IntegerField(default=0, editable=False)
    reply_count = models.IntegerField(default=0, editable=False)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return "%s - %s" % (self.title, self.forum.title)

    def num_posts(self):
        return self.posts.count()

    def num_replies(self):
        return self.num_posts() - 1

    def last_post(self):
        return first(self.posts.all())

    def inc_views(self):
        self.view_count += 1
        self.save()
        self.forum.inc_views()

    def update_reply_count(self):
        self.reply_count = self.posts.all().count()
        self.save()


class Post(models.Model):
    title = models.CharField(max_length=60)
    slug = models.CharField(max_length=60, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, blank=True, null=True)
    thread = models.ForeignKey(Thread, related_name="posts")
    body = models.TextField(max_length=10000)

    class Meta:
        ordering = ["created"]

    def __str__(self):
        return "%s" % self.title

    def editable(self, user):
        if user == self.creator:
            if timezone.now() < self.created + datetime.timedelta(**settings.FORUMS_EDIT_TIMEOUT):
                return True
        return False



@receiver(pre_save, sender=Forum)
def slugify_forum(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.title)

@receiver(pre_save, sender=Thread)
def slugify_thread(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.title + str(instance.id))

@receiver(pre_save, sender=Post)
def slugify_post(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.title)

@receiver(pre_save, sender=Category)
def slugify_category(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.name)

Forum/views.py
from braces.views import LoginRequiredMixin
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.utils.text import slugify
from django.views.generic import ListView, DetailView, CreateView
from Forum.models import Forum, Category, Thread, Post


class IndexListCategoryView(LoginRequiredMixin, ListView):
    model = Category


class IndexCategoryView(LoginRequiredMixin, DetailView):
    model = Category
    slug_field = 'slug'
    slug_url_kwarg = 'category'


class DetailForumView(LoginRequiredMixin, DetailView):
    model = Forum
    slug_field = 'slug'
    slug_url_kwarg = 'title'


class CreateThreadView(LoginRequiredMixin, CreateView):
    model = Thread
    fields = ('title',)
    template_name = 'Forum/create_thread.html'

    def get_success_url(self):
        return reverse('thread_detail', kwargs={'category': self.kwargs['category'],
                                                'title': self.kwargs['title'],
                                                'thread_name': Thread.objects.get(id=self.object.id).slug })

    def form_valid(self, form):
        thread = form.save(commit=False)


        thread.creator = self.request.user
        thread.forum = Forum.objects.get(slug=self.kwargs['title'])

        threadtmp = thread.save()
        # self.slug = slugify(self.object.title + str(self.object.id))
        return super(CreateThreadView, self).form_valid(form)


class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('body',)
    template_name = 'Forum/create_thread.html'

    def get_success_url(self):
        return reverse('thread_detail', kwargs={'category':self.kwargs['category'], 'title':self.kwargs['title'], 'thread_name':self.kwargs['thread_name']})

    #category=thread.forum.category.slug title=thread.forum.slug thread_name=thread.slug
    def form_valid(self, form):
        post = form.save(commit=False)
        post.creator = self.request.user
        post.title = self.kwargs['thread_name']
        post.thread = Thread.objects.get(forum__category__slug=self.kwargs['category'], slug=self.kwargs['thread_name'])
        post.save()
        return super(CreatePostView, self).form_valid(form)
    # title = models.CharField(max_length=60)
    # slug = models.CharField(max_length=60, blank=True)
    # created = models.DateTimeField(auto_now_add=True)
    # creator = models.ForeignKey(User, blank=True, null=True)
    # thread = models.ForeignKey(Thread, related_name="posts")
    # body = models.TextField(max_length=10000)

class DetailThreadView(LoginRequiredMixin, DetailView):
    model = Thread
    slug_field = 'slug'
    slug_url_kwarg = 'thread_name'


def index(request):
    return HttpResponse('Forum')

templates/Administration/forum/categories_list.html
{% extends 'Administration/admin_base.html' %}
{% load i18n %}
{% block body_title %}
    {% trans 'List of forum categories' %}
{% endblock %}
{% block body %}
    {% for category in category_list %}
    <p>{{ category }}</p>
    {% endfor %}

{% endblock %}

templates/Administration/forum/forum_list.html
{% extends 'Administration/admin_base.html' %}
{% load i18n %}
{% load static %}
{% block body_title %}
    {% trans 'Forum list' %}
{% endblock %}
{% block css %}
    <!-- DataTables CSS -->
    <link href="{% static 'PortalAdmin/css/external/dataTables.bootstrap.css' %}" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="{% static 'PortalAdmin/css/external/dataTables.responsive.css' %}" rel="stylesheet">
{% endblock %}
{% block body %}

    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                {% trans 'Advanced list forum' %}
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" role="grid" aria-describedby="dataTables-example_info">
                                    <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 280px;">{% trans 'Forum' %}</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 338px;">{% trans 'Threads' %}</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 315px;">Status</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 243px;">{% trans 'Category' %}</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 191px;">{% trans 'Position in category' %}</th></tr>
                                    </thead>
                                    <tbody>
                                    {% for forum in forum_list %}
                                        <tr class="gradeA {% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}" role="row">
                                            <td class="sorting_1"><a href="#">{{ forum }}</a></td>
                                            <td>{{ forum.threads.all|length }}</td>
                                            <td>{% if not forum.closed %}{% trans 'Open' %}{% else %}{% trans 'Closed' %}{% endif %}</td>
                                            <td>{{ forum.category.name }}</td>
                                            <td>{{ forum.position }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                {#                                <div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">Showing 1 to 10 of {{ user_list|length }} entries</div></div><div class="col-sm-6"><div class="dataTables_paginate paging_simple_numbers" id="dataTables-example_paginate"><ul class="pagination"><li class="paginate_button previous disabled" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_previous"><a href="#">Previous</a></li><li class="paginate_button active" aria-controls="dataTables-example" tabindex="0"><a href="#">1</a></li><li class="paginate_button " aria-controls="dataTables-example" tabindex="0"><a href="#">2</a></li><li class="paginate_button " aria-controls="dataTables-example" tabindex="0"><a href="#">3</a></li><li class="paginate_button " aria-controls="dataTables-example" tabindex="0"><a href="#">4</a></li><li class="paginate_button " aria-controls="dataTables-example" tabindex="0"><a href="#">5</a></li><li class="paginate_button " aria-controls="dataTables-example" tabindex="0"><a href="#">6</a></li><li class="paginate_button next" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_next"><a href="#">Next</a></li></ul></div></div></div></div>#}
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function() {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>

    <!-- DataTables JavaScript -->
    <script src="{% static 'PortalAdmin/js/external/jquery.dataTables.js' %}"></script>
    <script src="{% static 'PortalAdmin/js/external/dataTables.bootstrap.min.js' %}"></script>
{% endblock %}