Forum/urls.py
__author__ = 'Jordan'

from django.conf.urls import patterns, include, url
from django.contrib import admin
from .views import index, IndexListCategoryView, IndexCategoryView, DetailForumView, DetailThreadView, CreateThreadView, \
    CreatePostView

urlpatterns = patterns('',
    url(r'^$', IndexListCategoryView.as_view(), name='super_portal_index'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/$', IndexCategoryView.as_view(), name='category_detail_forum'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/$', DetailForumView.as_view(), name='forum_detail'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/create/$', CreateThreadView.as_view(), name='create_thread'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<thread_name>(?:\w+[-\t\n\r\f\v:]*\w+)+)/$', DetailThreadView.as_view(), name='thread_detail'),
    url(r'^(?P<category>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<title>(?:\w+[-\t\n\r\f\v:]*\w+)+)/(?P<thread_name>(?:\w+[-\t\n\r\f\v:]*\w+)+)/new/$', CreatePostView.as_view(), name='create_post'),

)

GuildPortal/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Portal.views import index
from django.contrib.auth import views as auth_view
from PortalAdmin.views import SignupView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'GuildPortal.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^forum/', include('Forum.urls')),
    url(r'^message/', include('PortalMessaging.urls')),
    url(r'^raid/', include('PortalRaid.urls')),
    url(r'^recrutement/', include('PortalEnrollment.urls')),
    url(r'^administration/', include('PortalAdmin.urls')),
    url(r'^accounts/login/', auth_view.login),
                       url(r"^account/signup/$",
                           SignupView.as_view(),
                           name="account_signup"),
    # url(r"^account/", include("account.urls")),
    url(r'', include('SuperPortal.urls')),
)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^media/news/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    }),
)

PortalRaid/urls.py
from PortalRaid.views import NewCharacterFormView, ServerListView, ListCharactersUser, DetailsCharacter,\
    DetailsCharacterFromAPI, RaidListView, RaidDetailView, SignUpRaidView, ClassCharacterAPI

__author__ = 'Alexandre Cloquet'

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       url(r'^$', RaidListView.as_view(), name='index_raid'),
                       url(r'^(?P<pk>\d+)/$', RaidDetailView.as_view(), name='raid_detail'),
                       url(r'^(?P<pk>\d+)/signup$', SignUpRaidView.as_view(), name='raid_detail_signup'),
                       url(r'^add_new_character/$', NewCharacterFormView.as_view(), name='new_character'),

                       url(r'^server_list$', ServerListView.as_view(), name='serverlist'),
                       url(r'^ClassCharacterAPI', ClassCharacterAPI.as_view(), name='ClassCharacterAPI'),

                       url(r'^list_characters_user/$', ListCharactersUser.as_view(), name='list_characters_user'),
                       url(r'^detail_characters/(?P<pk>\d+)/$', DetailsCharacter.as_view(), name='detail_characters'),
                       url(r'^detail_characters_from_api$', DetailsCharacterFromAPI.as_view(), name='detail_characters_from_api'),
                       )

PortalRaid/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext as _

# Create your models here.
from Portal.models import Game, CharacterAttribute


class CharacterModel(models.Model):
    user = models.ForeignKey(User)
    game = models.ForeignKey(Game, blank=True, null=True)
    name = models.CharField(_('Name'), max_length=50)
    server = models.ForeignKey('Realm')
    iLvl = models.IntegerField(_('iLvl'), default=0, null=True)
    url = models.URLField(null=True, blank=True)
    classCharacter = models.ManyToManyField(CharacterAttribute, verbose_name=_("Class for your character"))

    def __str__(self):
        return "%s: %s - %s : %s" % (self.user.username, self.name, self.game.name, self.server.name)

    class Meta:
        ordering = ('user',)
        verbose_name = _('Character')
        verbose_name_plural = _('Characters')


class Realm(models.Model):
    #TODO Faire une update admin pour remplir automatiquement
    game = models.ForeignKey(Game, blank=True, null=True)
    name = models.CharField(_('Realm name'), max_length=50)

    def __str__(self):
        return "%s - %s" %(self.game, self.name)

    class Meta:
        ordering = ('game',)
        verbose_name = _('Realm')
        verbose_name_plural = _('Realms')


class Raid(models.Model):
    name = models.CharField(_('Raid name'), max_length=64)
    game = models.ForeignKey(Game)
    lvl = models.ForeignKey('RaidLvl', null=True)
    number_of_boss = models.SmallIntegerField(_('Number of boss'))
    boss_successful = models.SmallIntegerField(_('Boss Successful'))
    image = models.ImageField(_('Image'), upload_to='portalraid/image/')

    def class_formatted_level(self):
        return self.lvl.name.replace(' ', '-')

    def get_progression_boss(self):
        return self.boss_successful * 100 / self.number_of_boss

    def get_out_raid(self):
        return self.outraid_set.all()

    def __str__(self):
        return "%s, %s - %s" % (self.name, self.game.name, self.lvl.name)

class Boss(models.Model):
    name = models.CharField(_('Boss name'), max_length=64)
    raid = models.ManyToManyField(Raid)
    position_in_raid = models.SmallIntegerField(_('Position in raid'), default=1)
    story = models.TextField(_('Story about this boss'))
    image = models.ImageField(_('Image'), upload_to='portalraid/boss/')

    def __str__(self):
        return "%s - %s" % (self.name, self.raid.name)

class RaidLvl(models.Model):
    name = models.CharField(_('Level name'), max_length=64, help_text=_("Normal mode, Heroic mode, Mythic mode"))

    def __str__(self):
        return "%s" % self.name

class GroupForRaid(models.Model):
    name = models.CharField(_('Name'), max_length=64)
    users = models.ManyToManyField(CharacterModel)


class ClassForOutRaid(models.Model):
    number = models.SmallIntegerField()
    classCharacter = models.ForeignKey(CharacterAttribute)

    def __str__(self):
        return "%d %s" % (self.number, self.classCharacter.attribute_value)

from datetime import datetime

class OutRaid(models.Model):
    name = models.CharField(_('Out name'), max_length=64)
    raid = models.ForeignKey(Raid)
    raid_lvl = models.ForeignKey(RaidLvl)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    creator = models.ForeignKey(User)
    class_needed = models.ManyToManyField(ClassForOutRaid)
    lvl = models.SmallIntegerField(_('Level'))

    def __str__(self):
        return "%s - %s => %s for %s" % (self.start_date, self.end_date, self.name, self.raid.name)

    def check_character_in(self, character):
        for character_out in self.characterforoutraid_set.all():
            if character == character_out.character:
                return True
        return False

    def get_characters(self):
        return self.characterforoutraid_set.all()

    def can_be_register(self):
        if self.start_date < datetime.now():
            return False
        return True

class CharacterForOutRaid(models.Model):
    out_raid = models.ForeignKey(OutRaid, blank=True, null=True)
    character = models.ForeignKey(CharacterModel)
    classCharacter = models.ForeignKey(CharacterAttribute)
    present = models.BooleanField(default=False)

PortalRaid/forms.py
from Portal.models import CharacterAttribute, TypeValue
from PortalRaid.models import CharacterModel, CharacterForOutRaid

__author__ = 'Alexandre Cloquet'

from django import forms

class CharacterForm(forms.ModelForm):
    class Meta:
        model = CharacterModel
        exclude = ('user', 'iLvl', 'url', 'classCharacter')
        widgets = {
            'game': forms.Select(attrs={
                'onchange': "serverAPI(this.value, this.id)"
            })
        }

class CharactersRaidForm(forms.ModelForm):
    class Meta:
        model = CharacterForOutRaid
        exclude = ('out_raid',)
        widgets = {
            'character': forms.Select(attrs={
                'onchange': "classforCharacterAPI(this.value, this.id)"
            })
        }

PortalRaid/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied, ValidationError
from django.core.urlresolvers import reverse, reverse_lazy
from django.forms import forms
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import ugettext as _

# Create your views here.
from django.utils.decorators import method_decorator
from django.views.generic import View, TemplateView, FormView, ListView, DetailView
from Portal.models import CharacterAttribute, TypeValue
from Portal.models.enrollment import Game
from Portal.models import CharacterAttribute, TypeValue, Game
from PortalRaid.forms import CharacterForm, CharactersRaidForm
from PortalRaid.models import Realm, CharacterModel, OutRaid, Raid


class RaidListView(ListView):
    model = OutRaid

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(RaidListView, self).dispatch(request, *args, **kwargs)

    def get_raids(self):
        game_choices = {}
        for game in Game.objects.all():
            choices = {}
            for raid in Raid.objects.all():
                if raid.game == game:
                    if raid.name not in choices:
                        choices[raid.name] = []
                    choices[raid.name].append(raid)
            game_choices[game.name] =  choices
        return game_choices

    def get_queryset(self):
        import datetime
        queryset = self.model.objects.filter(start_date__gte=datetime.datetime.today() - datetime.timedelta(minutes=30))
        return queryset


class RaidDetailView(DetailView):
    model = OutRaid
    context_object_name = 'raid'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(RaidDetailView, self).dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        outraid = get_object_or_404(self.model, pk=self.kwargs.get('pk', None))
        return outraid


class SignUpRaidView(FormView):
    form_class = CharactersRaidForm
    template_name = 'PortalRaid/signupforraid.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(SignUpRaidView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        out_raid = OutRaid.objects.get(id=self.kwargs['pk'])
        #TODO Verifier que le nombre de chaque class ne soit pas depasse
        if out_raid.can_be_register():
            for class_needed in out_raid.class_needed.all():
                if form.instance.classCharacter == class_needed.classCharacter:
                    form.instance.out_raid = out_raid
                    for char in out_raid.characterforoutraid_set.all():
                        if char.character == form.instance.character:
                            raise forms.ValidationError(
                                _('You have already sign up for this raid'),
                                code='invalid',
                            )
                        if char.character.user == self.request.user:
                            raise forms.ValidationError(
                                _('You have already register with another character'),
                                code='invalid',
                            )
                    form.save()
                    return super(SignUpRaidView, self).form_valid(form)
            raise forms.ValidationError(
                _('We don\'t need this class: %(value)s'),
                code='invalid',
                params={'value': form.instance.classCharacter.attribute_value},
            )
        raise forms.ValidationError(
            _('It\'s out of date of registration'),
            code='invalid'
        )


        #form.save()

    # def get_form_kwargs(self):
    #     kwargs = super(SignUpRaidView, self).get_form_kwargs()
    #     kwargs['user'] = self.request.user
    #     return kwargs


class ServerListView(View):
    """
    :return json for ajax request to have list of server for each game in select option
    """
    def get(self, request, *args, **kwargs):
        realms = Realm.objects.filter(game=request.GET['game'])
        # characters = CharacterAttribute.objects.filter(for_game=request.GET['game'], attribute_name=TypeValue.objects.get(field_value='Classe'))
        dict_for_json = dict()
        dict_for_json['realm'] = [{'id': realm.id, 'name': realm.name} for realm in realms]
        # dict_for_json['class'] = [{'id': char.id, 'name': char.attribute_value.field_value} for char in characters]
        return JsonResponse(dict_for_json, safe=False)


class ClassCharacterAPI(View):
    """
    :return json for ajax request to have list of server for each game in select option
    """

    def get(self, request, *args, **kwargs):
        characters = CharacterModel.objects.get(id=request.GET['character'])
        dict_for_json = dict()
        dict_for_json['class'] = [{'id': char.id, 'name': char.attribute_value.field_value} for char in characters.classCharacter.all()]
        return JsonResponse(dict_for_json, safe=False)


class DetailsCharacter(DetailView):
    model = CharacterModel
    context_object_name = 'character'

    def get_context_data(self, **kwargs):
        context = super(DetailsCharacter, self).get_context_data(**kwargs)
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(DetailsCharacter, self).dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        character =  get_object_or_404(self.model, pk=self.kwargs.get('pk', None))
        if character.user == self.request.user:
            return character
        raise PermissionDenied()


class DetailsCharacterFromAPI(View):
    def get(self, request, *args, **kwargs):
        char = CharacterModel.objects.get(pk=self.request.GET['char'])
        if char.user == self.request.user:
            #print self.request.GET['fields']
            from battlenet.community.wow.characters import Character
            print('Youhou')
            print(Character(name=char.name, realm=char.server.name, locale='fr', apikey="r5k3eqmj988fh6wsdvu8gh57rzbap62r"))
            tmp = Character(name=char.name, realm=char.server.name, locale='fr',
                            apikey="r5k3eqmj988fh6wsdvu8gh57rzbap62r").get(fields=['appearance', ])
            return JsonResponse(tmp[1], safe=False)


class ListCharactersUser(ListView):
    """
    :return List of all characters for each user
    """
    model = CharacterModel

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ListCharactersUser, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = self.model.objects.filter(user=self.request.user)
        return queryset


class NewCharacterFormView(FormView):
    """
    Allow to add new characters on website. User can select game and server on list.
    """
    template_name = 'PortalRaid/new_character.html'
    form_class = CharacterForm
    success_url = reverse_lazy('profile')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(NewCharacterFormView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):

        form.instance.user = self.request.user
        form.instance.url = form.instance.game.url_api or '' + 'character/' + form.instance.server.name + '/' + form.instance.name + '/'
        form.save()
        for x in CharacterAttribute.objects.filter(for_game=Game.objects.filter(id=self.request.POST['game'])).distinct('attribute_name'):
            form.instance.classCharacter.add(CharacterAttribute.objects.filter(attribute_name=x.attribute_name, id=self.request.POST[x.attribute_name.field_value]).first())
        form.save()
        return super(NewCharacterFormView, self).form_valid(form)

templates/PortalRaid/new_character.html
{% extends 'SuperPortal/base.html' %}
{% load static %}
{% load i18n %}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'PortalEnrollment/css/enrollment.css' %}">
{% endblock %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        function serverAPI(value, id) {
            var game_name = $("select#"+id+" option:selected").text();
            $('div#characters-attribute').load('{% url 'character_attributes' %}' + '?game='+ encodeURI(game_name))
            $.ajax({
                url: '{% url 'serverlist' %}' + '?game=' + value

            }).success(function(json) {
                $('#id_server').empty();
                $('#id_classCharacter').empty();
                console.log(json.class);
                $.each(json.realm, function(i, value) {
                    $('#id_server').append($('<option>').text(value['name']).attr('value', value['id']));
                });
                $.each(json.class, function(i, value) {
                    $('#id_classCharacter').append($('<option>').text(value['name']).attr('value', value['id']));
                });

            })
        }

        function charactersAPI(data, selector) {
            var game_name = $("select#"+selector+" option:selected").text();
            $('div#characters-attribute').load('{% url 'character_attributes' %}' + '?game='+ encodeURI(game_name))
        }

    </script>
{% endblock %}
{% block meta_description %}{% trans 'Profile' %}: {{ user.username }}{% endblock %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        <div class="field-wrapper col-xs-12">
            <div class="col-xs-12 col-lg-8 col-lg-offset-2 content-wrapper">
                {{ form.game.errors }}
                <label for="{{ form.game.id_for_label }}">{{ form.game.label }}: </label>
                <hr>
                <div class="field-wrapper-content">
                    {{ form.game }}
                    <div id="characters-attribute"></div>
                </div>
            </div>
        </div>

        <div class="field-wrapper col-xs-12">
            <div class="col-xs-12 col-lg-8 col-lg-offset-2 content-wrapper">
                {{ form.name.errors }}
                <label for="{{ form.name.id_for_label }}">{{ form.name.label }}: </label>
                <hr>
                <div class="field-wrapper-content">
                    {{ form.name }}
{#                    <div id="characters-attribute"></div>#}
                </div>
            </div>
        </div>
        <div class="field-wrapper col-xs-12">
            <div class="col-xs-12 col-lg-8 col-lg-offset-2 content-wrapper">
                {{ form.server.errors }}
                <label for="{{ form.server.id_for_label }}">{{ form.server.label }}: </label>
                <hr>
                <div class="field-wrapper-content">
                    {{ form.server }}
{#                    <div id="characters-attribute"></div>#}
                </div>
            </div>
        </div>
{#        <div class="field-wrapper col-xs-12">#}
{#            <div class="col-xs-12 col-lg-8 col-lg-offset-2 content-wrapper">#}
{#                {{ form.classCharacter.errors }}#}
{#                <label for="{{ form.classCharacter.id_for_label }}">{{ form.classCharacter.label }}: </label>#}
{#                <hr>#}
{#                <div class="field-wrapper-content">#}
{#                    {{ form.classCharacter }}#}
{#                    <div id="characters-attribute"></div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
        <div class="col-xs-12 col-lg-1 col-lg-offset-9 content-wrapper">
            <input type="submit">
        </div>
    </form>

{% endblock %}

templates/PortalRaid/outraid_detail.html
{% extends 'SuperPortal/base.html' %}
{% load i18n %}
{% load static %}
{% block css %}
    {{ block.super }}

    <link rel="stylesheet" href="{% static 'PortalRaid/css/profil.css' %}">
{% endblock %}
{% block meta_description %}{% trans 'Profile' %}: {{ user.username }}{% endblock %}

{% block body %}
    <div class="col-xs-10 col-xs-offset-1 content-wrapper">
        <a href="{% url 'raid_detail_signup' raid.id %}">{% trans 'Sign up' %}</a>
        <div id="header-raid" class="col-xs-3">
            <img class="img-responsive" src="{{ raid.raid.image.url }}">
        </div>
        <div id="out-raid" class="col-xs-7">
            <h3>{{ raid.name }}</h3>
            <h5>{{ raid.raid.name }} {% trans 'for' %} {{ raid.raid.game.name }} {% trans 'in' %} {{ raid.raid.lvl.name }}</h5>
            <p>{% trans 'Start date' %}: {{ raid.start_date }}</p>
            <p>{{ raid.characterforoutraid_set.all|length }} {% trans 'registered' %} - {% trans 'Level required' %} {{ raid.lvl }}</p>
            <div id="raid">
                <div class="progress">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="{{ raid.raid.get_progression_boss }}"
                         aria-valuemin="0" aria-valuemax="100" style="width:{{ raid.raid.get_progression_boss }}%">
                        {{ raid.raid.boss_successful }} / {{ raid.raid.number_of_boss }} {% trans 'Boss' %}
                    </div>
                </div>
            </div>
        </div>
        <div id="required" class="col-xs-7">
            {% for class_needed in raid.class_needed.all %}
                <h4>{{ class_needed.number }} - {{ class_needed.classCharacter.attribute_value }}</h4>
                <ul>
                    {% for character in raid.characterforoutraid_set.all %}
                        {% ifequal class_needed.classCharacter.attribute_value character.classCharacter.attribute_value %}
                            <li>
                                <p>
                                    {% if character.character.user.userprofile.image_profile %}
                                        <img src="{{ character.character.user.userprofile.image_profile.url}}" height="40" width="40">
                                    {% else %}
                                        <img src="" height="40" width="40">
                                    {% endif %}
                                    <b>{{ character.character.user.username }}</b> {% trans 'sign up with' %} {{ character.character.name }} {% trans 'as' %} {{ character.classCharacter.attribute_value.field_value }}</p></li>
                        {% endifequal %}
                    {% endfor %}
                </ul>
            {% endfor %}
        </div>
        {% for boss in raid.raid.boss_set.all %}
            {% if boss.position_in_raid == raid.raid.boss_successful %}
                <div id="header-raid" class="col-xs-3">
                    <img class="img-responsive" src="{{ boss.image.url }}">
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

templates/PortalRaid/outraid_list.html
{% extends 'SuperPortal/base.html' %}
{% load i18n %}
{% load static %}
{% block css %}
    {{ block.super }}

    <link rel="stylesheet" href="{% static 'PortalRaid/css/profil.css' %}">
{% endblock %}

{% block js %}
    {{ block.super }}

    <script type="text/javascript">

        $(document).ready(function () {
            $('a.raid-lvl').each(function() {
                console.log('allo');
                $(this).on('click', function() {
                    attr = $(this).attr('raid-lvl');
                    console.log('div.raid-level.' + attr);
                    $(this).parent().find('div.raid-lvl').each(function(){
                        $(this).fadeOut()
                    });
                    $(this).parent().find('div.raid-lvl.' + attr).fadeIn()
                })
            })

        })


    </script>

{% endblock %}

{% block meta_description %}{% trans 'Profile' %}: {{ user.username }}{% endblock %}

{% block body %}
    <div class="col-xs-12 col-lg-10 col-lg-offset-1 content-wrapper">
        {% if outraid_list %}
            <h2>{% trans 'Schedule Raid' %}</h2>
            {% for raid in outraid_list %}
                <div id="header-raid" class="col-xs-3">
                    <img class="img-responsive" src="{{ raid.raid.image.url }}">
                </div>
                <div id="out-raid" class="col-xs-7">
                    <h3>{{ raid.name }}</h3>
                    <h5>{{ raid.raid.name }} {% trans 'for' %} {{ raid.raid.game.name }} {% trans 'in' %} {{ raid.raid.lvl.name }}</h5>
                    <p>{% trans 'Start date' %}: {{ raid.start_date }}</p>
                    <p>{{ raid.characterforoutraid_set.all|length }} {% trans 'registered' %} - {% trans 'Level required' %} {{ raid.lvl }}</p>
                    <div id="raid">
                        <div class="progress">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="{{ raid.raid.get_progression_boss }}"
                                 aria-valuemin="0" aria-valuemax="100" style="width:{{ raid.raid.get_progression_boss }}%">
                                {{ raid.raid.boss_successful }} / {{ raid.raid.number_of_boss }}
                            </div>
                        </div>
                    </div>
                </div>
                <a href="{% url 'raid_detail' raid.id %}">{% trans 'Detail' %}</a> | <a href="{% url 'raid_detail_signup' raid.id %}">{% trans 'Sign up' %}</a>
            {% empty %}
                <h3>{% trans 'No raid schedule at this time' %}</h3>
                <img class="img-responsive" src="http://digital-art-gallery.com/oid/19/611x945_5124_WoW_crying_tree_2d_fan_art_druid_wow_world_of_warcraft_fantasy_picture_image_digital_art.jpg">
            {% endfor %}
        {% endif %}
    <hr>
        <div class="list-raid col-xs-12">
            <h2>{% trans 'Progress Raid' %}</h2>
            {% for game, raids in view.get_raids.items %}
                <div class="game-raid col-xs-12">
                    <h2> {{ game }}</h2>
                    {% for raidname, raids in raids.items %}
                        <div>
                            <h4>{{ raidname }}</h4>
                            {% for raid in raids %}
                                <a href="javascript:void(0)" class="raid-lvl" raid-lvl="{{ raid.class_formatted_level }}">{{ raid.lvl }}</a>
                            {% endfor %}
                            {% for raid in raids %}
                                {% include 'PortalRaid/raid.html' %}
                            {% endfor %}
                        </div>
                    {% empty %}
                        <p>{% trans 'No raid at this time' %}</p>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>








        {#        {% for raid in view.get_raids %}#}
        {#            <h2>{{ raid.name }} {% trans 'in' %} {{ raid.lvl.name }}</h2>#}
        {#            <div id="raid">#}
        {#                <h4>{% trans 'Progress' %}</h4>#}
        {#                <div class="progress">#}
        {#                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="{{ raid.raid.get_progression_boss }}"#}
        {#                         aria-valuemin="0" aria-valuemax="100" style="width:{{ raid.get_progression_boss }}%">#}
        {#                        {{ raid.boss_successful }} / {{ raid.number_of_boss }}#}
        {#                    </div>#}
        {#                </div>#}
        {#            </div>#}
        {#            <div class="boss-down col-xs-12">#}
        {#                <h4>{% trans 'Boss down' %}</h4>#}
        {#                {% for boss in raid.boss_set.all %}#}
        {#                    {% if raid.boss_successful >= boss.position_in_raid %}#}
        {#                        <div class="boss col-xs-2">#}
        {#                            <h5>{{ boss.name }}</h5>#}
        {#                            <img src="{{ boss.image.url }}" class="img-responsive">#}
        {#                            <p>{{ boss.story|linebreaks }}</p>#}
        {#                        </div>#}
        {#                    {% endif %}#}
        {#                {% endfor %}#}
        {#            </div>#}
        {##}
        {#        {% endfor %}#}
    </div>


{% endblock %}